---
:fixtures:
  :datasets:
    :set1:
      :rules:
        :body: :body
      :definition:
        :name: test dataset
        :body: test placeholderbody
    :set2:
      :definition:
        :name: test dataset 2
        :body: 
      :rules:
        :body: :body
    :set3:
      :definition:
        :name: test dataset 3 
        :body: test preserved
      :rules:
        :body: :preserve_body
    :set4:
      :definition:
        :name: test dataset 4
        :nested:
          :body: 
      :rules:
        :body: :body
    :set5:
      :definition:
        :name: test dataset 5
        :list:
         - 1
         - :body: 
         - 3
        :nested:
          :body: 
      :rules:
        :body: :body
    :set6:
      :definition:
        - :name: test dataset 6
          :list:
            - 1
            - :body: 
            - 3
          :nested:
            :body:
        - "deux" 
      :rules:
        :body: :body
  :rules:
    :body: 
      :proc: "SecureRandom.urlsafe_base64(64)"
    :preserve_body:
      :preserve: true
      :proc: "SecureRandom.urlsafe_base64(64)"
  :models:
    :type: :mongoid
    :order:
      - :posts
      - :comments
    :definitions:
      :posts:
        :rules:
          :body: :preserve_body
        :class: Post
        :unicity: :id
        :collection:
          - :attributes:
              :title: First post Title
              :body: First Post Body
          - :attributes:
              :title: Second post Title
              :body: 
      :comments:
        :class: Comment
        :unicity: :id
        :collection:
          - :attributes:
              :name: test name
              :message: test message
            :links:
              - :collection: :posts
                :index:
                  :at: 1
                :fkey: :post
                :pkey: :id