---
:fixtures:
  :datasets:
    :myset:
      :definition:
        - :name: test dataset
          :list:
            - 1
            - :body: 
            - 3
          :nested:
            :body:
        - "two" 
      :rules:
        :body: :body

  :rules:
    :body: 
      :proc: "SecureRandom.urlsafe_base64(64)"
    :preserve_body:
      :preserve: true
      :proc: "SecureRandom.urlsafe_base64(64)"
  :models:
    :type: :mongoid
    :order:
      - :posts
      - :comments
    :definitions:
      :posts:
        :rules:
          :body: :preserve_body
        :class: Post
        :unicity: :title
        :collection:
          - :attributes:
              :title: First post Title
              :body: First Post Body
          - :attributes:
              :title: Second post Title
              :body: 
      :comments:
        :class: Comment
        :unicity: :id
        :collection:
          - :attributes:
              :name: test name
              :message: test message
            :link:
              :to: :posts
              :by: :comments
              :search_by:  
                :title: First post Title