require_relative 'dependencies'
require_relative 'fixturizer/settings'
require_relative 'fixturizer/configuration'
require_relative 'fixturizer/adapters/init'
require_relative 'fixturizer/engines/init'
require_relative 'fixturizer/serializers/init'
require_relative 'fixturizer/services'